  -- MySQL Script generated by MySQL Workbench
  -- Mon Feb 25 16:35:05 2019
  -- Model: New Model    Version: 1.0
  -- MySQL Workbench Forward Engineering

  -- -----------------------------------------------------
  -- Table `db_control_clientes`.`tbl_usuarios`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `db_control_clientes`.`tbl_usuarios` (
    `rpe` VARCHAR(12) NOT NULL PRIMARY KEY,
    `nombre` VARCHAR(25) NULL,
    `apellidos` VARCHAR(45) NULL,
    `email` VARCHAR(45) NULL,
    `telefono` VARCHAR(45) NULL,
    `username` VARCHAR(15) NULL,
    `password` VARCHAR(32) NULL,
    `estado` INT(1) NULL,
    `rol` INT(1) NULL)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `db_control_clientes`.`tbl_cliente`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `db_control_clientes`.`tbl_clientes` (
    `rpu` VARCHAR(12) NOT NULL PRIMARY KEY,
    `nombre` VARCHAR(30) NULL,
    `apellidos` VARCHAR(50) NULL,
    `direccion` VARCHAR(45) NULL,
    `colonia` VARCHAR(45) NULL,
    `cp` VARCHAR(45) NULL,
    `telefono` VARCHAR(25) NULL,
    `cuenta` VARCHAR(45) NULL,
    `tarifa` VARCHAR(45) NULL,
    `fecha_alta` VARCHAR(45) NULL,
    `hilos` VARCHAR(45) NULL,
    `sts-servicio` VARCHAR(45) NULL,
    `email` VARCHAR(45) NULL,
    `rfc` VARCHAR(45) NULL,
    `rainting` INT(5) NULL)
    ENGINE = InnoDB;


  -- da5fcb6c28d91fa10d80ac559e7e0cb8

  -- -----------------------------------------------------
  -- Table `db_control_clientes`.`tbl_llamada`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `db_control_clientes`.`tbl_llamadas` (
    `id_llamada` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    `solucion` LONGTEXT NULL,
    `importe` DOUBLE(12,3),
    `fk_rpu` VARCHAR(12) NOT NULL,
    `fk_rpe` VARCHAR(12) NOT NULL)
  ENGINE = InnoDB;
  
  ALTER TABLE `tbl_llamadas`
  ADD CONSTRAINT `fk_rpe`
  FOREIGN KEY (`fk_rpe`)
  REFERENCES `tbl_usuarios` (`rpe`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  